var P = {
  items:[
    {
      name:'Become an Affiliate',
      thumbnail:'become_an_affiliate',
      description:'',
      link:'liquid/become-an-affiliate',
      year:'2018',
      tags:{
        javascript:true,
        landingPage:true,
        responsive:true,
        ui:false,
        ux:false,
      }
    },
    {
      name:'',
      thumbnail:'',
      description:'',
      link:'',
      year:'',
      tags:{
        javascript:,
        landingPage:,
        responsive:,
        ui:,
        ux:,
      }
    },
    {
      name:'',
      thumbnail:'',
      description:'',
      link:'',
      year:'',
      tags:{
        javascript:,
        landingPage:,
        responsive:,
        ui:,
        ux:,
      }
    },
    {
      name:'two'
    },
    {
      name:'three'
    },
  ],
  map:{
    javascript:'JavaScript',
    landingPage:'Laning Page',
    responsive:'Responsive',
    ui:'UI',
    ux:'UX'
  }
}